name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  gatsby-for-percy:
    name: Percy screenshots via Gatsby build
    runs-on: ubuntu-latest
    env:
      PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          cache: 'npm'
          node-version: '14'
        env:
          FONTAWESOME_NPM_AUTH_TOKEN: ${{ secrets.FONTAWESOME_NPM_AUTH_TOKEN }}
      - run: |
          npm config set '//npm.fontawesome.com/:_authToken' "${{ secrets.FONTAWESOME_NPM_AUTH_TOKEN }}"
          npm ci
      - run: npx gatsby clean
      - run: npx gatsby build --prefix-paths
      - run: npx percy snapshot -t 10000 ./public
