on:
  push:
    branches:
      - 'staging'
  pull_request:
    types:
      - closed
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - uses: actions/checkout@v3
      - run: git config user.name github-actions
      - run: git config user.email github-actions@github.com
      - run: mkdir ../old
      - run: mkdir ../new
      - run: mv ./* ../old
      - run: git clone https://github.com/prisma/docs --branch release ../new
      - run: mv ../new ./new
      - run: mv ../old ./old
      - run: wget https://raw.githubusercontent.com/prisma/docs-tools/main/script/migration/migration.py > ./migration.py
      - run: wget https://raw.githubusercontent.com/prisma/docs-tools/main/script/migration/const.py > ./const.py
      - run: wget https://raw.githubusercontent.com/prisma/docs-tools/main/script/migration/stitched.py > ./stitched.py
      - run: wget https://raw.githubusercontent.com/prisma/docs-tools/main/script/migration/api.py > ./api.py
      - run: wget https://raw.githubusercontent.com/prisma/docs-tools/main/script/migration/config.json > ./config.json
      - run: mv migration.py.1 ./migration.py
      - run: mv const.py.1 ./const.py
      - run: mv stitched.py.1 ./stitched.py
      - run: mv api.py.1 ./api.py
      - run: mv config.json.1 ./config.json
      - run: pip install requests
      - run: python migration.py
      - run: cd ./new
      - run: git add --all
      - run: git commit -m "generated"
      - run: git checkout -b release
      - run: git push origin release
