name: Documentation Checks

on:
  push:
    branches:
      - main
    paths:
      - "content/**/*"
  pull_request:
    branches:
      - main
    paths:
      - "content/**/*"
jobs:
  spellcheck:
    name: "Docs: Spellcheck"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Check out the code
      - uses: actions/setup-node@v6
        name: Setup node
        with:
          node-version: "22"
      - run: npm install -g cspell
        name: Install cSpell
      - run: cspell --config ./cSpell.json "content/**/*.mdx" --no-progress
        name: Run cSpell
